shotgunsoftware/tk-multi-loader2

- python/tk_multi_loader/delegate_publish_list.py
Show the task info on the list view in the loader:
Always show it since we have the space and the logic about when it is shown or not in the Thumbnail view can be a little subtle and non-obvious.
> Ticket #30252 - Show task info in the lists delegate.

- python/tk_multi_loader/dialog.py
This fixes a bug which would sometimes cause the loader to not respond correctly the very first time after launch that a tab in the left hand side tree view was clicked.
> #25280 Clicking on tab now always shows the list of items in tree

- python/tk_multi_loader/proxymodel_entity.py
The left hand side tree view is now shorted alphabetically:
Previously, it would just display the raw data as it was being sent from the shotgun model. The shotgun model does not imply any ordering of the data, this is left to the client to handle (since it typically varies between use cases and sometimes, like in the case of the loader, you want to do a bunch of post processing of the raw model data before you have access to the display name which you want to order by).
> #38761 Tree view sorted alphabetically

- info.yml
- python/tk_multi_loader/constants.py
- python/tk_multi_loader/dialog.py
- python/tk_multi_loader/proxymodel_entity.py
This updates the loader to work correctly with the new optimized shotgun model that defer loads things into memory.
- the filtering is 'capped' so that it doesn't kick in until you have typed 2 characters.
- the entire tree is loaded into memory at this point in order for the proxy model to operate.
> #39260 filter support for new shotgun model

- info.yml
- python/tk_multi_loader/delegate_publish_list.py
- python/tk_multi_loader/delegate_publish_thumb.py
- python/tk_multi_loader/dialog.py
- python/tk_multi_loader/model_hierarchy.py
- python/tk_multi_loader/model_item_data.py
- python/tk_multi_loader/model_latestpublish.py
Handle a new configuration setting option that adds the capability to define left hand side tabs driven by the new Shotgun hierarchy model.
> #37239: Use the new tree widget for Loader hierarchy navigation.

- hooks/tk-3dsmaxplus_actions.py
Evaluates maxscript to generate a bitmap texture referencing the publish. Attaches it to a default material so that it shows in the material editor. Also pops up the material editor to make it obvious.
> #41925 Adds texture node loading in 3dsmax

- hooks/tk-flame_actions.py
- info.yml
DESCRIPTION
This adds functionality to the tk-flame part of the Shotgun Loader
Now a user can Create a batch group using the supported clips linked to
a Shot entity. Once this Batch group is created, if the user have the
right context (Classic integration for now with the tk-flame-export),
a Render will trigger a publish export to Shotgun.
There's also more configuration options. Theses options allow the user
to change certain behavior of the loader without having to play in the
Python code.
Finally, there's more documentation and more debug logging to be able to
do better troubleshooting.
> SMOK-29361 | tk-flame_action improved

- app.py
The app init requires PySide, and that's not guaranteed to be available when there's no GUI.
> For #40555: Stops app init if there's no UI.

- python/tk_multi_loader/delegate_publish_history.py
This changes the behaviour of the sg panel so that if you click the "play" icon for a version, it will navigate you to the sg media center page rather than screening room which was previously the case. Back when we originally wrote this code, the media center was not yet released and they did not have proper urls that you can navigate to. This change aligns the behaviour in the loader with what you get in the the sg web app.
> #43996 Clicking play in sg panel navigates to sg media player

- hooks/tk-nuke_actions.py
This is resolving an issue in zero config projects. The frame range parsing logic on load in Nuke uses templates to parse the file name. Since we do not have access to templates in a zero config setup, we are forced to instead parse the file name based on some commonly-used conventions.
Note: Nuke does its own frame range parsing when browsing for a frame sequence on disk from the browse button in a read node, however, this functionality is not publicly available via Python. After digging around forums a bit, it looks like people implement their own solutions in Python similar to what I did here. In fact, Foundry provides a tutorial for implementing a managed read node and in that tutorial they provide an example implementation that determines the start/end frames for frame sequences. …
> For #44569: Implements file name parsing to determine start and end frame numbers.

- hooks/tk-houdini_actions.py
the Unicode flag was causing problems in regex sub operation. Houdini does not accept special characters (é, à,..) when creating nodes. We replace these by '_', along with non alphanumeric characters.
> #45167 removed unicode flag from regex sub operation

- python/tk_multi_loader/model_latestpublish.py
This fixes a bug which previously prevented you to configure the loader in a way so that you would be browsing *Versions* in the left hand side tree and when you clicked a version you would see the publishes associated with that version.
> #46438 support for version based workflows

- python/tk_multi_loader/dialog.py
- python/tk_multi_loader/utils.py
Now allows complex filters to be used when specifying the filters for tabs.
For example the filters in the tab settings bellow would not work previous to the update.
```
- caption: Tasks
entity_type: Task
filters:
- [project, is, "{context.project}"]
- filter_operator: "any"
filters:
- [entity, type_is, Asset]
- [entity, type_is, Shot]
```
I have taken the code from the [workfiles2 way of resolving the filters](https://github.com/shotgunsoftware/tk-multi-workfiles2/blob/master/python/tk_multi_workfiles/util.py#L282-L314). I've also moved the logic for resolving filters out into utils, as this is what wf2 does as well.
However I also noticed that the workfiles way of doing it doesn't resolve the project from the context, so I've made a hybrid of the two bits of logic.
For SG-5399
> SG-5399 Added support for complex filters

- hooks/tk-nuke_actions.py
This is a cleaned-up implementation of client PR #66. It implements a new loader action capable of importing publishes as clips in Nuke Studio and Hiero.
> For SG-5387: Adds support for importing publishes as Hiero/Nuke Studio clips.

- python/tk_multi_loader/model_publishtype.py
This ensures we end up with the "folders" type after a hard refresh of the model. This is a very minor change that pairs with an accompanying fix for ShotgunModel's hard_refresh functionality in the more general sense.
> SG-6836: Implements a hard_refresh method on the publish type model.

- python/tk_multi_loader/delegate_publish_list.py
- python/tk_multi_loader/delegate_publish_thumb.py
- python/tk_multi_loader/dialog.py
Currently the delegated widgets are using the entity type. We replaced this value with the entity display name.
> Replaced entity type with entity display name

- hooks/tk-photoshopcc_actions.py
- python/tk_multi_loader/banner.py
Fixes the Photoshopcc hook so that it works in Python 3.
Also fixed a `QAnimationGroup::animationAt: index is out of bounds` warning that was being raised when showing the banner for the second time. This was caused by the animation objects getting garbage collected.
> Python 3 fix for Photoshop

- hooks/tk-maya_actions.py
Updated to work with Python 3 and converted pymel use to the supported Autodesk APIs.
> Python 3 Maya hooks update

- python/tk_multi_loader/delegate_publish_list.py
- python/tk_multi_loader/delegate_publish_thumb.py
This is a complement of a previous pull request to display the entity's name instead of the entity's type.
In the image "CustomEntity07" is not a proper name and can confuse users.
> Display entity name instead entity type

- azure-pipelines.yml
- tests/test_gui.py
Adding Azure Agent Name to Shotgun project name.
Like that, the Shotgun project will not be overwritten when we will run the UI automation on both, Python 2 and 3
> Adding Azure Agent Name to Shotgun project name

- python/tk_multi_loader/dialog.py
This PR fix the issue in which the wrong tab(first tab) in the Loader  app is opened when the Loader is launched in a task context. Now the tab related to the 'entity_type' specified in the tk-multi-loader2.yml is opened.
> SG-31007 Loader2 wrong tab/entity selected by default in task context

- python/tk_multi_loader/dialog.py
* Currently file items in Loader can be dragged around (click + hold and move)
* Set movement to static so that items stay in place
This is under the assumption that items are not meant to be draggable. I could not find any evidence that this is the desired case.
> SHOT-4295: Do not allow items to be dragged around

- info.yml
- python/tk_multi_loader/dialog.py
- python/tk_multi_loader/model_latestpublish.py
- python/tk_multi_loader/proxymodel_latestpublish.py
- python/tk_multi_loader/ui/dialog.py
- resources/dialog.ui
There are some minor differences between using the old Published File Type filter widget compared to the new filter menu. If users prefer the old way, they can turn that back on using the new config option. Note that the legacy filter widget cannot be used with the new Filter menu, it is one or the other due to synchronization issues when both filtering is shown.
This also resolves issue for SHOT-4294: when using the new filter menu, only show published file types that are defined via the config.
The code in this PR is almost all strictly adding back functionality from v1.22.1 - no new functionality.
> SHOT-4297/SHOT-4294: Add config option to use legacy filter widget and fix show only types from config

- app.py
I've noticed a funny behaviour where the `publish_types` keywordsometimes doesn't take effect on the first time `Multiloader.open_publish()` is called.
It was probably from `Multiloader.open_publish()` being called somewhere else previously and having it's mutable kwarg polluted.
See also:
- https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
- https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html
> SG-34348 Fixed mutable keyword argument: Multiloader.open_publish

- app.py
- info.yml
- python/tk_multi_loader/api/manager.py
* Allow passing a Tank bundle (e.g. App, Engine, Framework) to create the Loader Manager api, so that the Loader api can be used from other Toolkit apps and use that app's settings (instead of only the Loaders settings, this allows the loader api to generate and execute actions  defined by other apps)
* Allow defining key `All` in the config settings to add actions for all published file types (currently you have to define the action for each file type)
_Example usage in Breakdown2: https://github.com/shotgunsoftware/tk-multi-breakdown2/pull/77_
- _Breakdown2 uses the Loader api to create/execute actions, while the Breakdown2 App itself just needs to define the actions in its config setting_
> SHOT-4292: Improve API

- python/tk_multi_loader/dialog.py
This seems suspicious at first, but it makes sense when it's compared to a known issue in Qt6 environments like this fix: https://github.com/shotgunsoftware/tk-framework-qtwidgets/pull/161
> SG-35445 Handle exception on Qt6
